---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - microsegment.io
  resources:
  - clusterprofiles
  - pceconnections
  - policyinsights
  - ruleviews
  - segmentationintents
  - segmentationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsegment.io
  resources:
  - clusterprofiles/status
  - pceconnections/status
  - policyinsights/status
  - ruleviews/status
  - segmentationintents/status
  - segmentationpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsegment.io
  resources:
  - segmentationintents/finalizers
  - segmentationpolicies/finalizers
  verbs:
  - update
